### ISSUE TITLE
`require': cannot load such file -- alfresco4r (LoadError)

### ISSUE THREAD

**Issue by gitarrenlia** [sivaprakasamboopathy/alfresco4r#1]
Hi, I've got a problem when trying to require alfresco4r to my Rubyscript.

When I try to run a script starting with: require 'alfresco4r', I get the Error: `require': cannot load such file -- alfresco4r (LoadError)

I ran "sudo gem install alfresco4r" before and I work on a debian system.

I hope anyone can help me with this issue.

**Comment by b-siva** [comment]
Thanks for the notifying the issue, new gem version 1.0.0 is published which solves the load error.
